### ISSUE TITLE
Connect Twitter

### ISSUE THREAD

**Issue by IsaacMiguel** [mdemblani/twitter-client#1]
Hi! I have a problem when i try on function connect.
The app init well, no problem with credentials.
No modification from my side, just put all the files in a server and try it.

this is the response: 
{"success":false,"message":"JSON.parse: unexpected character at line 1 column 1 of the JSON data"}

Hope we can help and use this aproach.
Thanks!

**Comment by mdemblani** [comment]
Sure, I'll check it. In the mean time, if you have a pull request for the same, feel free to send it through.

**Comment by mdemblani** [comment]
@IsaacMiguel Can you elaborate more in-detail about the steps you had taken, to the point you faced the problem.

**Comment by mdemblani** [comment]
Closing the issue due to inactivity.
